sudo: required

services:
  - docker

before_install:
  - docker build -t mukulb77/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mukulb77/multi-docker  npm test

after_success:
  - docker build -t mukulb77/multi-client ./client
  - docker build -t mukulb77/multi-nginx ./nginx
  - docker build -t mukulb77/multi-server ./server
  - docker build -t mukulb77/multi-worker ./worker

  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mukulb77/multi-client
  - docker push mukulb77/multi-nginx
  - docker push mukulb77/multi-server
  - docker push mukulb77/multi-worker
